# Generated by Django 4.2 on 2023-04-27 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2023, 4, 27, 15, 32, 0, 148612, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
    ]
